search_products:
  description: >
    Search for a product {query} in the attached Google Sheet.
    Provide the most relevant products and recommended products information 
    based on the user query.
  expected_output: >
    A JSON object with keys "products" and "message".
  agent: search_agent

recommend_products:
  description: >
    Analyze the search tool's output, which includes both the search_products and 
    recommended_products.
    Once you find the relevant products and recommendations, do not start researching
    from scratch.
    Present the searched products and recommendations without adding new products.

  expected_output: >
    A JSON object with keys "products" and "recommended_products".
  agent: recommendation_agent


interaction_task:
  description: >
    Facilitate an interactive shopping experience by engaging in conversation with 
    the user.
    Present product search results, recommendations.
    Do not add any additional products or recommendations, which you get from the
    recommendation agent.
    Your core task is to interact with the user and guide them through the shopping 
    process without adding new products. 
    Your next task, when you receive the results, is to assist user with 
    refining searches, sorting selections, reverting previous choices, 
    and confirming actions like adding items to the cart.
  expected_output: >
    - A dynamic and interactive conversation where users can refine their searches. 
    - Allow users to Sort or filter product lists based on results provided by the 
      recommendation agent.
    - Ability to revert to previous selections if requested. 
    - Confirmation of actions like adding items to the cart or proceeding to checkout.
  agent: interaction_agent


# cart_task:
#   description: >
#     Handle add/remove actions for products in the cart and wishlist.
#   expected_output: >
#     An updated cart or wishlist reflecting user selections.
#   agent: cart_manager

# checkout_task:
#   description: >
#     Guide the user through the checkout process and ensure a successful transaction.
#   expected_output: >
#     A completed order confirmation and successful payment guidance.
#   agent: checkout_agent

# support_task:
#   description: >
#     Answer common questions and assist users with any shopping or order-related issues.
#   expected_output: >
#     Helpful responses addressing user concerns and guiding them to solutions.
#   agent: support_agent
