search_products:
  description: >
    Search for a product {query} in the attached Google Sheet.
    Provide the most relevant product information based on the user query.
    Your entire response must be valid JSON strictly following the schema:
    {{
      "products": [ {{"name": <str>, "price": <float>, "category": <str>, "description": <str|null>}} ],
      "message": <str|null>
    }}
    Do not include any additional text, markdown, or explanations.
  expected_output: >
    A JSON object with keys "products" and "message".
  agent: search_agent



# recommend_products:
#   description: >
#     Analyze the user's search results and extract the category of the products. 
#     If the category format required by the Furniture Recommendation Tool is not found, 
#     you are smart enough to ensure you can convert the category into the correct format.
#     Make a search for the products in the attached Google Sheet based on the category.
#     e.g. if search results are category": "Living Room" then make a search for the 
#     products in the attached Google Sheet based on the category "Living Room".
#     Provide the products with brief descriptions and the reason for the recommendation.
#     Utilize the attached Google Sheet to analyze available inventory and ensure relevant suggestions.
#   expected_output: >
#     A curated list of recommended furniture products from the attached Google Sheet, 
#     with brief descriptions and the reason for the recommendation.
#   agent: recommendation_agent


interaction_task:
  description: >
    Facilitate an interactive shopping experience by engaging in conversation with the user. 
    Present product search results, assist with refining searches, sorting selections, 
    reverting previous choices, and confirming actions like adding items to the cart.
  expected_output: >
    - A dynamic and interactive conversation where users can refine their searches. 
    - Sorted or filtered product lists based on user query and the category of the products. 
    - Ability to revert to previous selections if requested. 
    - Confirmation of actions like adding items to the cart or proceeding to checkout.
  agent: interaction_agent


# cart_task:
#   description: >
#     Handle add/remove actions for products in the cart and wishlist.
#   expected_output: >
#     An updated cart or wishlist reflecting user selections.
#   agent: cart_manager

# checkout_task:
#   description: >
#     Guide the user through the checkout process and ensure a successful transaction.
#   expected_output: >
#     A completed order confirmation and successful payment guidance.
#   agent: checkout_agent

# support_task:
#   description: >
#     Answer common questions and assist users with any shopping or order-related issues.
#   expected_output: >
#     Helpful responses addressing user concerns and guiding them to solutions.
#   agent: support_agent
